// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKDMpmCgMHmOzEdpsIyewPOpN2YRch7yA',
    appId: '1:504359343948:android:1aef6085b17bb840b4a1e9',
    messagingSenderId: '504359343948',
    projectId: 'elevenai',
    databaseURL: 'https://elevenai-default-rtdb.firebaseio.com',
    storageBucket: 'elevenai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowleD_GI7a_l-JWnfDvGcfUtEDdQGvqM',
    appId: '1:504359343948:ios:be75bd11301f326fb4a1e9',
    messagingSenderId: '504359343948',
    projectId: 'elevenai',
    databaseURL: 'https://elevenai-default-rtdb.firebaseio.com',
    storageBucket: 'elevenai.appspot.com',
    androidClientId: '504359343948-7ji1gpg2h6rt7vofbpudf9mj5epr8sft.apps.googleusercontent.com',
    iosClientId: '504359343948-fkal2bdjfuuqnb25hsr9b8o7qc6osip3.apps.googleusercontent.com',
    iosBundleId: 'com.souradeep.elevenAi',
  );
}
